---
# tasks file for grafana

- name: install from apt
  become: true
  apt: 
    deb: https://dl.grafana.com/oss/release/grafana_9.2.1_amd64.deb
  
- name: Start grafana-server Service
  become: true
  systemd:
    state: started
    name: grafana-server
    enabled: yes

- name: Check if grafana was accessible
  uri:
    url: http://localhost:3000
    method: GET
    status_code: 200
