- name: Check if prometheus is installed.
  stat: "path=/usr/local/bin/prometheus"
  register: prometheus_bin

- name: Check if alertmanager is installed.
  stat: "path=/usr/local/bin/alertmanager"
  register: alertmanager_bin

- name: Unarchive prometheus x64
  become: true
  unarchive: 
    src: https://github.com/prometheus/prometheus/releases/download/v2.37.5/prometheus-2.37.5.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: not prometheus_bin.stat.exists


- name: create prometheus configuration directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/backup"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/file_sd"
    - "{{ prometheus_db_dir }}"
  when: not prometheus_bin.stat.exists

- name: prometheus Service systemd
  become: true
  template: 
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: prometheus Service Config
  become: true
  template: 
    src: prometheus.yaml.j2
    dest: /etc/prometheus/prometheus.yaml

- name: Copy config prometheus target
  become: true
  template:
    src: targets.yaml.j2
    dest: /etc/prometheus/targets.yaml

- name: Just force systemd to reread configs (2.4 and above)
  become: true
  systemd:
    daemon_reload: yes

- name: Start prometheus Service
  become: true
  systemd:
    state: started
    name: prometheus
    enabled: yes
  when: not prometheus_bin.stat.exists

- name: Restart prometheus Service
  become: true
  systemd:
    state: restarted
    name: prometheus
    enabled: yes
  when: alertmanager_bin.stat.exists


- name: Check if prometheus is accessible
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200
